### ISSUE TITLE
"Clear all" button not shown in recents view

### ISSUE THREAD

**Issue by sreinst1** [scotthartbti/android_packages_apps_Settings#12]
Under Beanstalk options -> Misc options -> Recents view settings, the "Clear all button" seems to have no effect. Even when marked, the button does not show up when showing the recents view (no matter if it's slim recents or not).

**Comment by ghost** [comment]
The "Clear all" button is working for me. It does not show in "slim recents" but other than that it seems to be working fine...

**Comment by sreinst1** [comment]
You are absolutely right... sorry for the false report. It doesn't work
only in slim recents view. At first I didn't see it because it was
configured but default to bottom left where the recents are shown...
בתאריך 12 במרץ 2014 23:51, "Johnny Dennis" notifications@github.com כתב:

**Comment by sreinst1** [comment]
But hey, it does not work with slim recents... I think it's still an issue.
בתאריך 13 במרץ 2014 00:07, "Johnny Dennis" notifications@github.com כתב:

**Comment by ghost** [comment]
I haven't really looked but I'm pretty sure that the "clear all" button is only supposed to work in the "normal" recents but I'll wait for scott to weigh in on this ;)

If he says it's a bug I'll look at it...

**Comment by scotthartbti** [comment]
This.  Johnny is 100 percent correct.  I'll edit the strings to clarify.  I
could set it as a dependent, but its setup backwards and slim recents would
have to be the default... Which I don't want.  Johnny if you could go ahead
and close this again please.

**Comment by ghost** [comment]
Thanks for the clarification ...  ;)

**Comment by sreinst1** [comment]
Thanks also!
