### ISSUE TITLE
QS: "Flip tiles" cannot be deactivated

### ISSUE THREAD

**Issue by sreinst1** [scotthartbti/android_packages_apps_Settings#13]
The following option does not seem to work:
Settings > BeanStalk options > Notification & QS drawer > Style > Flip tiles

The tiles are always flipped on touch, even if the checkbox is not marked.

**Comment by ghost** [comment]
fixed: https://github.com/scotthartbti/android_packages_apps_Settings/commit/a0858448a89867933705edaa80a6332829413f55

**Comment by sreinst1** [comment]
Thanks!

**Comment by sreinst1** [comment]
Sorry for writing it here (I don't know how else to ask): Is there some guide for the features of this ROM? There are lots of features I am not familiar with, and I'm afraid to try some of them.

**Comment by scotthartbti** [comment]
There are numerous YouTube vids out there for beanstalk on different
devices.  Besides that you have the changelog (which admittedly I need to
do a better job keeping up to date).  Other then that, play with shit and
see what it all does... It won't break anything.
