### ISSUE TITLE
Missing second row Pie option

### ISSUE THREAD

**Issue by kenzolo** [scotthartbti/android_packages_apps_Settings#14]
There is no option to disable/edit second row pie
![screenshot_2014-03-16-14-40-47](https://f.cloud.github.com/assets/5021409/2430964/d5624e90-ad10-11e3-882a-62b30e4cbc36.png)

**Comment by scotthartbti** [comment]
There isn't supposed to be an option.  Its static and how its supposed to
be via the slimrom developers.

**Comment by kenzolo** [comment]
Are you sure scott?
I think there is an issue in the commit cause in  other rom I can see the option...
and here you can read

https://github.com/SlimRoms/packages_apps_Settings/commit/b84104dcbe1b8cd722ee034ae215918ed69ec79b

"Other unique thing of SlimPie
is that 2 rows are available. First row user can setup up to 5 buttons. On the second
row up to 7 Buttons."

**Comment by kenzolo** [comment]
For example this is carbon rom PIE option
![screenshot_2013-01-01-01-01-40](https://f.cloud.github.com/assets/5021409/2431041/171b0114-ad17-11e3-9191-23dae3ad0881.png)

**Comment by scotthartbti** [comment]
Sorry for doubting you.  Fixed small derp to show second layer button options with this commit faaf713ada3de1b5ac59d36b2b830ddd7c2112f2
