### ISSUE TITLE
Building:Error: No resource found that matches the given name

### ISSUE THREAD

**Issue by moonlightly** [scotthartbti/android_packages_apps_Settings#5]
packages/apps/Settings/res/xml/propmodder.xml:23: error: Error: No resource found that matches the given name (at 'title' with value '@string/performance_settings_warning_title').
packages/apps/Settings/res/xml/system_ui_settings.xml:17: error: Error: No resource found that matches the given name (at 'title' with value '@string/system_interface_title').

**Comment by scotthartbti** [comment]
Hmm... Wtf didn't I get this when I built?  I'll take care of it in a second.

**Comment by scotthartbti** [comment]
Fixed with commit 5be96d7ccfe339186d2bbaeff8677008d5157626

Please let me know if you find any other missing strings ASAP.

**Comment by moonlightly** [comment]
Thanks,I'll build it after about 10 hours and see the results.if have another I'll tell you!
