### ISSUE TITLE
Use my Strings and build but Settings.apk not have these language 

### ISSUE THREAD

**Issue by moonlightly** [scotthartbti/android_packages_apps_Settings#6]
HI, I have added my our strings to values-zh-rCN folder  and set build's folder to en_US zh_TW zh_CN zh_HK,when build complete and flash to my phone,Settings.apk only have English,How to fix it

**Comment by moonlightly** [comment]
Settings.apk in every languages are only show english

**Comment by scotthartbti** [comment]
Fixed with commit d80dc74108938dfade2cef84db8fad59aec6907a
